CREATE TABLE SINHVIEN (
    MaSV CHAR(12) NOT NULL,
    HoSV VARCHAR(50),
    TenSV VARCHAR(10),
    NgaySinh DATE,
    DiaChi VARCHAR(100),
    Phai NVARCHAR(3),
    Nam CHAR(9),
    Khoa VARCHAR(50)
);
   
ALTER TABLE SINHVIEN ADD PRIMARY KEY (MaSV); -- thêm khóa chính cho bảng SINHVIEN

CREATE TABLE GIANGVIEN (
    MaGV CHAR(4) NOT NULL,
    HoGV NVARCHAR(50),
    TenGV NVARCHAR(10),
    NgaySinh DATE,
    DiaChi NVARCHAR(100),
    Phai VARCHAR(10),
    ChuyenNganh NVARCHAR(50),
    Khoa VARCHAR(50)
);
ALTER TABLE GIANGVIEN ADD PRIMARY KEY (MaGV); -- thêm khóa chính cho bảng GIANGVIEN



CREATE TABLE MONHOC (
    MaMH CHAR(4) PRIMARY KEY,
    TenMH NVARCHAR(50),
    SoTinChi INT,
    Loai BIT,
    Khoa VARCHAR(50)
);

CREATE TABLE DIEUKIEN(
    MaMH CHAR(4) NOT NULL,
    MaMHTruoc CHAR(4) NOT NULL,
    PRIMARY KEY (MaMH),
    FOREIGN KEY (MaMHTruoc) REFERENCES MONHOC(MaMH)
);

ALTER TABLE MONHOC ADD PRIMARY KEY (MaMH,MaMHTruoc); -- thêm khóa chính cho bảng MONHOC

ALTER TABLE DIEUKIEN ADD FOREIGN KEY (MaMH) REFERENCES MONHOC(MaMH); -- thêm khóa ngoại cho bảng DIEUKIEN
CREATE TABLE KHOAHOC(
    MaKH CHAR(3) PRIMARY KEY,
    MaMH CHAR(4),
    HocKy INT,
    MaGV CHAR(4),
    TenKH VARCHAR(50),
    NamHoc CHAR(9),
    Khoa VARCHAR(50)
);

ALTER TABLE DIEUKIEN ADD PRIMARY KEY (MaKH,MaMH); -- thêm khóa chính cho bảng KHOAHOC

ALTER TABLE KHOAHOC ADD CONSTRAINT Kh_Mh FOREIGN KEY (MaMH) REFERENCES MonHoc(MaMH); -- thêm khóa ngoại cho bảng KHOAHOC

ALTER TABLE KHOAHOC ADD CONSTRAINT Kh_Gv FOREIGN KEY (MaGV) REFERENCES GIANGVIEN(MaGV);
CREATE TABLE KETQUA(
    MaSV CHAR(12),
    MaKH CHAR(3),
    Diem FLOAT,
    KetQua NVARCHAR(50)
);


ALTER TABLE KETQUA ADD CONSTRAINT Kq_Sv FOREIGN KEY (MaSV) REFERENCES SINHVIEN(MaSV);

ALTER TABLE KETQUA ADD CONSTRAINT Kq_Kh FOREIGN KEY (MaKH) REFERENCES KHOAHOC(MakH);